name: test-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  - master

pr:
  - master

pool: TESTpool

variables:
  - group: Secret variables
  - name: projectName
    value: test

stages:
  - stage: CI
    displayName: Test full image
    jobs:
      - job: test
        displayName: Test full image
        steps:
          - checkout: self

          - task: DockerCompose@0
            displayName: docker compose build --no-cache test
            env:
              DOCKER_BUILDKIT: "1"
              COMPOSE_DOCKER_CLI_BUILD: "1"
              TEST_USERNAME: $(TEST_USERNAME)
              TEST_PASSWORD: $(TEST_PASSWORD)
            inputs:
              action: Run a Docker Compose command
              dockerComposeFile: $(Build.SourcesDirectory)/docker-compose.yml
              dockerComposeCommand: build --no-cache test
              projectName: $(projectName)
              dockerComposePath: docker-compose

          - task: DockerCompose@0
            displayName: docker compose up test
            env:
              DOCKER_BUILDKIT: "1"
              COMPOSE_DOCKER_CLI_BUILD: "1"
              TEST_USERNAME: $(TEST_USERNAME)
              TEST_PASSWORD: $(TEST_PASSWORD)
            inputs:
              action: Run a Docker Compose command
              dockerComposeFile: $(Build.SourcesDirectory)/docker-compose.yml
              dockerComposeCommand: up --abort-on-container-exit test
              projectName: $(projectName)
              dockerComposePath: docker-compose
