x-app-volumes: &app-volumes
  - .:/app
  - /app/.venv
  - /app/.uv
  - /app/.spark-work
  - /app/.git

secrets:
  username:
    environment: USERNAME
  password:
    environment: PASSWORD

services:
  test-base:
    build:
      context: .
      dockerfile: Dockerfile
    image: test-base:latest
    volumes: *app-volumes
    working_dir: /app

  test:
    profiles:
      - full
    build:
      context: .
      dockerfile: Dockerfile-full
      args:
        BASE_IMAGE: test-base:latest
      secrets:
        - username
        - password
    image: test:latest
    depends_on:
      - test-base
    environment:
      UV_INDEX_DPS_USERNAME: ${USERNAME:-}
      UV_INDEX_DPS_PASSWORD: ${PASSWORD:-}
    volumes: *app-volumes
    working_dir: /app
